export const ENUMS = {
  tipoAmbiente: [
    'COZINHA', 'VARANDA', 'GOURMET', 'AREA_SERVICO', 'LAVANDERIA', 'SALA_ESTAR', 'HOME_THEATER', 'CINEMA', 'LIVING',
    'HALL', 'ESCRITORIO', 'BRINQUEDOTECA', 'ROUPEIRO', 'CIRCULACAO', 'SUITE', 'SUITE_01', 'SUITE_02', 'SUITE_03', 'SUITE_04',
    'CLOSET', 'CLOSET_01', 'CLOSET_02', 'CLOSET_03', 'CLOSET_04', 'BANHEIRO', 'BANHEIRO_O1', 'BANHEIRO_O2', 'BANHEIRO_O3',
    'BANHEIRO_O4', 'BANHEIRO_O5', 'LAVABO', 'LAVABO_01', 'LAVABO_02', 'LAVABO_03',
  ],
  acabamentoInterno: [
    'SIRENA', 'NOCE_DI_MILANO', 'SABBIA', 'AZZURO', 'CEMENTO_NOBILE', 'BIANCO_CARRARA', 'EXPRESSO_NOBILE', 'LEGNO_SOLE',
    'GRIGIO_PERLA', 'ROVERE', 'LEGNO_VIVO', 'ROSSO_TOSCANO', 'OLIVA_DOLCE', 'ORO', 'NOTTE', 'CASTAGNA_REALE', 'PETROLIO',
    'LINO_GREZZO', 'NEBBIA_BIANCA', 'EBANO_IMPERIALE', 'ROSA_MINERALE', 'VERDE_BOSCO', 'TOSCANO_SECCO', 'LACA',
  ],
  acabamentoExterno: [
    'SIRENA', 'NOCE_DI_MILANO', 'SABBIA', 'AZZURO', 'CEMENTO_NOBILE', 'BIANCO_CARRARA', 'EXPRESSO_NOBILE', 'LEGNO_SOLE',
    'GRIGIO_PERLA', 'ROVERE', 'LEGNO_VIVO', 'ROSSO_TOSCANO', 'OLIVA_DOLCE', 'ORO', 'NOTTE', 'CASTAGNA_REALE', 'PETROLIO',
    'LINO_GREZZO', 'NEBBIA_BIANCA', 'EBANO_IMPERIALE', 'ROSA_MINERALE', 'VERDE_BOSCO', 'TOSCANO_SECCO', 'LACA',
  ],
  acabamentoPerfil: [
    'NATURAL', 'PRETO', 'BRANCO', 'DOURADO', 'CHAMPAGNE', 'BRONZE', 'INOX', 'COBRE', 'NOTTE_6005_R80B', 'GRIGIO_PERLA_5000_N',
    'CIMENTO_NOBILE_3502_Y', 'EXPRESSO_NOBILE_4502_Y', 'ROSA_MINERALE_2010_G30Y', 'PETROLEO_6010_R90B',
  ],
  acabamentoTelinha: [
    'TELINHA_06OCSE80', 'TELINHA_06OCSE80_ESCURA', 'TELINHA_06OCSE80_PINTADA', 'TELINHA_07TC', 'TELINHA_07TC_ESCURA',
    'TELINHA_07TC_PINTADA', 'TELINHA_07T19', 'TELINHA_07T19_ESCURA', 'TELINHA_07T19_PINTADA', 'TELINHA_ESPECIAL',
  ],
  tipoPorta: [
    'RETA', 'LINEA', 'TURIM', 'ALUWAVE', 'PROVENCAL', 'RIPADA', 'RIPADA_VAZADA', 'TELINHA', 'MOLDURA_MDF', 'MOLDURA_VIDRO',
    'VIDRO', 'VITRINA', 'CRISTALEIRA_PROVENCAL', 'FRIZARE', 'ELISSE', 'MUXARABI', 'RITRATO', 'DIAMANTE', 'ESPECIAL',
  ],
  tipoPortaPassagem: ['PORTA_PIVOTANTE', 'PORTA_DOBRADICA_INVISIVEL', 'PORTA_CORRER', 'PORTA_VIDRO_PIVOTANTE', 'PORTA_VIDRO_CORRER', 'PORTA_MUXARABI'],
  tipoPuxador: [
    'CAVA_ALUMINIO', 'CAVA_ALUMINIO_LED', 'TURIM', 'LINEA_TOTAL', 'LINEA_100MM', 'LINEA_150MM', 'LINEA_200MM', 'PASSANTE_10MM',
    'PASSANTE_CAVA', 'PASSANTE_COCHO', 'TIPO_ONE', 'EXTERNO_ZEN', 'EXTERNO_OBISPA', 'ESPECIAL',
  ],
  tipoVidro: [
    'ESPELHO_PRATA', 'ESPELHO_FUME', 'ESPELHO_BRONZE', 'REFLECTA_INCOLOR', 'REFLECTA_FUME', 'REFLECTA_BRONZE', 'TRANSLUCIDO_CLEAR',
    'TRANSLUCIDO_COMUM', 'CANELADO', 'MINI_BOREAL', 'PINTADO', 'ESPECIAL',
  ],
  tipoCorredica: ['TANDEM_TOTAL', 'LEGRABOX_PURE', 'LEGRABOX_FREE', 'ANTARO', 'TELESCOPICA', 'ESPECIAL'],
  tipoDobradica: ['COMUM', 'COMUM_180', 'IKS', 'INVISIVEL', 'ESPECIAL'],
  tipoAventos: ['HKXS', 'HK', 'HF', 'HL', 'HS', 'PISTAO_INVERSO'],
  tipoAcessorio: [
    'PRATELEIRAS_VEGAS', 'PRATELEIRAS_CURVE', 'PRATELEIRAS_RAFINATTA', 'TAMPO_MAKEUP', 'SAPATEIRA_INCLINADA',
    'SAPATEIRA_INCLINADA_RAFINATTA', 'TAMPO_RAFINATTA_TESTEIRA', 'PERFIL_CURVE', 'PERFIL_PAINEL', 'PROTETOR_STUCCO',
    'DIVISOR_MDF', 'DIVISOR_ACRILICO', 'DIVISOR_TALHER_MDF', 'DIVISOR_TALHER_MADEIRA', 'DIVISOR_TALHER_ORGALINE',
    'DIVISOR_TALHER_ABIALINE', 'ORGANIZADOR_PRATOS', 'PORTA_FACAS', 'CORTA_FOLHAS', 'PORTA_CONDIMENTOS',
    'TAPETE_EMBORRACHADO', 'RODIZIO', 'SAPATA', 'TESTEIRA',
  ],
  tipoCabideiro: [
    'CABIDEIRO_COMUM', 'CABIDEIRO_COMUM_PINTADO', 'CABIDEIRO_CLOSET_ABERTO_COMUM', 'CABIDEIRO_CLOSET_ABERTO_COMUM_PINTADO',
    'CABIDEIRO_METAL_DESIGNE', 'CABIDEIRO_METAL_DESIGNE_LED', 'CABIDEIRO_ESPECIAL',
  ],
  tipoLed: ['PADRAO_OG', 'ARTETILICA', 'METAL_DESIGNE', 'ESPECIAL'],
  tipoPainel: [
    'PAINEL_LISO', 'PAINEL_RIPADO', 'PAINEL_FRISO_10MM', 'PAINEL_RIPA_SOBREPOSTA', 'PAINEL_PROVENCAL', 'PAINEL_FRIZARE',
    'PAINEL_TELINHA', 'PAINEL_MOLDURA_TELINHA', 'PAINEL_CURVO', 'PAINEL_MUXARABI', 'PAINEL_TRELICA', 'PAINEL_VIDRO',
    'PAINEL_RAFINATTA', 'PAINEL_ELISSE', 'PAINEL_ELISSE_CURVE',
  ],
  tipoRodape: ['MDF', 'ALVENARIA'],
  materiaisMdf: ['MDF BRANCO', 'MDF ROSA', 'MDF VERDE', 'MDF CINZA', 'MDF FREIJO', 'MDF PRETO'],
};

export function formatEnumLabel(value) {
  return String(value)
    .replaceAll('_', ' ')
    .toLowerCase()
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}
